### ISSUE TITLE
DNSSEC not working in docker

### ISSUE THREAD

**Issue by pandalec** [jpillora/docker-dnsmasq#13]
Hey!
If I want to enable DNSSEC it states that dnsmasq is compiled without DNSSEC:
```
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify dumpfile

⁣⁣dnsmasq: unsupported option (check that dnsmasq was compiled with DHCP/TFTP/DNSSEC/DBus support) at line 6 of /etc/dnsmasq.conf

dnsmasq: DNSSEC not available: set HAVE_DNSSEC in src/config.h
```
(line 6 is "trust-anchor=...")
I use jpillora/dnsmasq:latest

**Comment by jpillora** [comment]
dnsmasq comes precompiled, straight out of the edge Alpine package repo. So
I'm guessing you'd need to compile a version yourself. Please send PR if
you get it to work :)

**Comment by pandalec** [comment]
You're right. Works like a charm :)
Just changed the precompiled version to the dnssec version. Thanks :)
