### ISSUE TITLE
(Request) webproc listen port option.

### ISSUE THREAD

**Issue by tokohito** [jpillora/docker-dnsmasq#17]
Hello Dear

My name is tokohito.
Thanks your great job!

I also use docker-dnsmasq as DNS and DHCP Server.
So I have to set network settings as "host mode".

This is an example of a command that I actually use.
> $ sudo docker run --name dnsmasq -d --restart always --network host --privileged -v /var/data/dnsmasq.conf:/etc/dnsmasq.conf --log-opt "max-size=100m" -e "HTTP_USER=admin" -e "HTTP_PASS=password" jpillora/dnsmasq

Unfortunately, the 8080 port that webproc uses by default conflicts with other products.
So I want to be  change to webproc listen port to any user-specified setting.
e.g)
-e "HTTP_PORT=5380"

I'm glad if you change the docker image like that.

Best regards!

**Comment by jpillora** [comment]
You should be able to set the PORT variable

This should be documented, and maybe should be HTTP_PORT instead...

**Comment by tokohito** [comment]
Hello Dear.

Thank your reply.
I tried to re-run docker by adding the "HTTP_PORT" option.
But unfortunately listen on port 8080 instead of the port I specified.

>$ sudo docker run --name dnsmasq -d --restart always --network host --privileged -v /var/data/dnsmasq.conf:/etc/dnsmasq.conf --log-opt "max-size=100m" -e "HTTP_USER=admin" -e "HTTP_PASS=password" -e "HTTP_PORT=5380" jpillora/dnsmasq
>$ sudo lsof -i -P | grep 8080
>webproc   11869            root    3u  IPv6 1431783      0t0  TCP *:8080 (LISTEN)
>webproc   11869            root    9u  IPv6 1434085      0t0  TCP hostserver:8080->192.168.0.100:57490 (ESTABLISHED)


Could you give me some advice?
regards.

**Comment by jpillora** [comment]
Use PORT

**Comment by tokohito** [comment]
Oops! Sorry.

Thanks for solving it.

I close this case.
