### ISSUE TITLE
windows can't get domain name resolution record

### ISSUE THREAD

**Issue by changeflyhigh** [jpillora/docker-dnsmasq#25]
Hi, Mr. Jpillora:

I set up a dns server refer to official articles " https://hub.docker.com/r/jpillora/dnsmasq"
dnsmasq-ip 10.2.1.137
CentOS-ip 10.2.1.138
Windows-ip 172.21.16.235

The contents of the document “dnsmasq.conf ” are as follows
log-queries
no-hosts
no-resolv
cache-size=1000
server=114.114.114.114
address=/harbor-zhc.zy.com/10.2.1.138

It run well for CentOS Server , but not for Windows. For example:

Running this command in CentOS:
$ nslookup harbor-zhc.zy.com 10.2.1.137
Server:		10.2.1.137
Address:	10.2.1.137#53

Name:	harbor-zhc.zy.com
Address: 10.2.1.138

Running this command in Windws:
C:\Users\admin>nslookup harbor-zhc.zy.com 10.2.1.137
服务器:  UnKnown
Address:  10.2.1.137

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时

**dnsmasq log when windows access:**
⁣⁣dnsmasq: query[PTR] 137.1.2.10.in-addr.arpa from 172.21.16.235
⁣⁣dnsmasq: forwarded 137.1.2.10.in-addr.arpa to 114.114.114.114
⁣⁣dnsmasq: reply 10.2.1.137 is NXDOMAIN
⁣⁣dnsmasq: query[AAAA] harbor-zhc.zy.com from 172.21.16.235
⁣⁣dnsmasq: config harbor-zhc.zy.com is NODATA-IPv6
⁣⁣dnsmasq: query[AAAA] harbor-zhc.zy.com from 172.21.16.235
⁣⁣dnsmasq: config harbor-zhc.zy.com is NODATA-IPv6

------
This problem has been bothering me for two days. I have searched a lot of articles and still can't solve it
Look forward to your reply,  thank you so much！

**Comment by changeflyhigh** [comment]
When I test dnsmasq in Virtual Machine（VIrtualBox）and windows, It work well. But the dnsmasq from IDC can't not. So I decided that there was something wrong with the network between windows and IDC room.
------
I'm sorry. I hope I haven't disturbed you

**Comment by fengzhao** [comment]
> ## When I test dnsmasq in Virtual Machine（VIrtualBox）and windows, It work well. But the dnsmasq from IDC can't not. So I decided that there was something wrong with the network between windows and IDC room.
> I'm sorry. I hope I haven't disturbed you

你的问题解决了？是网络原因吗？
